name: CI

on:
  push:
    branches: [ main, master]

jobs:
  test-app-server:
    name: app-server
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./laboratorioingweb/backend/app-server

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalamos Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app-server/package-lock.json

      - name: Instalamos dependencias del app-server
        run: npm ci

  test-gateway:
    name: gateway
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./laboratorioingweb/backend/gateway

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalamos Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: gateway/package-lock.json

      - name: Instalamos dependencias del gateway
        run: npm ci
